"""empty message

Revision ID: 55d8186870ce
Revises: 
Create Date: 2017-11-01 11:09:01.571965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d8186870ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('kennel_num', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('location_x', sa.Integer(), nullable=False),
    sa.Column('location_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('found_time', sa.DateTime(), nullable=True),
    sa.Column('found_location_x', sa.Integer(), nullable=False),
    sa.Column('found_location_y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('shelter')
    op.drop_table('city')
    # ### end Alembic commands ###
